#include "api.h"
#include "sdk.c"
#include "gme_media.h"   /* MEDIA_START / MEDIA_DONE -- our own synthetic IMA-ADPCM WAV cues,
                          * generated by gen_sounds.py and bundled as media[0]/media[1] by build_dumper.sh */

/*
 * memimg -- one-shot memory imager for the tiptoi pen (ONE PASS).
 *
 * Dumps the high-value memory regions to the PC-visible USB drive (B: root) in a SINGLE main()
 * call, inside the first-time-exec block -- exactly like the proven earlier dumper. (An earlier
 * "one region per event-loop tick" version produced NOTHING past the first call: the firmware
 * does not reliably re-enter main() for this purpose, so everything must happen in one pass.)
 *
 * We do NOT re-stream the full 3.5MB PROG image: we already have MT's PROG statically. We grab the
 * things we DON'T have: the resident HAL/nandboot, the runtime-populated data/bss (statechart
 * descriptor table, the runtime-init "keystone" vtable, globals), plus a couple of PROG anchors to
 * confirm pen==MT. Files: B:/mAAAAAAAA.bin, named by hex start address.
 *
 * SAFETY (empirical, real pens):
 *  - reading UNMAPPED memory powers the pen OFF.  -> regions are ordered SAFE-FIRST: the two
 *    confirmed-mapped ones (already dumped successfully before) lead, then likely-mapped live data,
 *    then the ONE untested region (HAL @0x07ff8000) LAST. If a read powers the pen off, every
 *    region before it is already on disk.
 *  - write() HANGS on >=1MB writes.  -> every write is a single 32KB chunk.
 *  - keep the pass short: ~14 writes total (the earlier working dumper did ~11).
 */

static const unsigned int regions[] = {
    /* --- confirmed mapped (both dumped OK on hardware already) --- */
    0x08120000u,   /* runtime statechart descriptor table 0x08121d44 (+ handler dispatch table) */
    0x08007000u,   /* statechart control block + low globals */
    /* --- the prize: runtime-init keystone + globals (live PROG data). Dumped 3rd, right after the
     *     two confirmed-safe regions, so we get it before any untested address. --- */
    0x081d8000u,   /* KEYSTONE vtable obj 0x081db984 / null slot +0xc = 0x081db990, pMeGame, playlist, audio */
    0x081d0000u,   /* globals just below the keystone cluster */
    0x081e0000u,   /* globals just above */
    0x0811e000u,   /* descriptor-table band (below 0x08120000) */
    0x08128000u,   /* descriptor-table band (above) */
    0x081c8000u,   /* globals band */
    0x081e8000u,   /* globals band (top) */
    /* NOTE: the low firmware region 0x08000000..0x08008000 is DROPPED -- a 32KB read there crashed a
     *       real pen (an unmapped hole below 0x08007000). We already have MT's PROG code statically. */
    /* --- untested mapping: the resident HAL/nandboot. LAST, so its risk can't cost us the rest. --- */
    0x07ff8000u,   /* pen's real boot loader -- shows the actual on-chip ANYKANB magic empirically */
};
#define NREG (int)(sizeof(regions)/sizeof(regions[0]))

static int done;
static unsigned short nm[18];

static void mkname(unsigned int a) {
    static const char hx[] = "0123456789abcdef";
    int i;
    nm[0]='B'; nm[1]=':'; nm[2]='/'; nm[3]='m';
    for (i = 0; i < 8; i++) nm[4+i] = (unsigned short)hx[(a >> ((7 - i) * 4)) & 0xf];
    nm[12]='.'; nm[13]='b'; nm[14]='i'; nm[15]='n'; nm[16]=0;
}
static void dump(unsigned short *path, void *src, unsigned int len) {
    int f = api->open(path, 1, 1);
    api->write(f, src, len);
    api->close(f);
}
static void log_line(unsigned short *path, const char *s, unsigned int n) {
    int f = api->open(path, 1, 1);
    api->write(f, (void *)s, n);
    api->close(f);
}

/* ------------------------------------------------------------------------- *
 * Growing diagnostic log (B:/TTMDUMP.LOG).  open(path,1,1) is create/write
 * (truncate-on-create; see fs_open/File_Open), so we keep the whole log text
 * in RAM and REWRITE the file after every line.  That makes each step commit
 * (close flushes) and a partial/crashed run leaves a complete log up to the
 * last step.  Small (<8KB) writes -- never near the >=1MB write() hang.
 * ------------------------------------------------------------------------- */
static char nlog_buf[0x2000];
static unsigned int nlog_n;
static void nlog_flush(void) {
    int f = api->open(L"B:/TTMDUMP.LOG", 1, 1);
    api->write(f, nlog_buf, nlog_n);
    api->close(f);
}
static void nlog_s(const char *s) {
    while (*s && nlog_n < sizeof(nlog_buf) - 1) nlog_buf[nlog_n++] = *s++;
}
static void nlog_hex(unsigned int v) {
    static const char hx[] = "0123456789abcdef";
    int i;
    nlog_s("0x");
    for (i = 7; i >= 0; i--)
        if (nlog_n < sizeof(nlog_buf) - 1) nlog_buf[nlog_n++] = hx[(v >> (i * 4)) & 0xf];
}
static void nlog_h8(unsigned int v) {   /* 8 hex digits, NO "0x" -- for exact filenames */
    static const char hx[] = "0123456789abcdef";
    int i;
    for (i = 7; i >= 0; i--)
        if (nlog_n < sizeof(nlog_buf) - 1) nlog_buf[nlog_n++] = hx[(v >> (i * 4)) & 0xf];
}
static void nlog_dec(unsigned int v) {
    char t[12]; int i = 0;
    if (v == 0) { nlog_s("0"); return; }
    while (v) { t[i++] = (char)('0' + v % 10); v /= 10; }
    while (i--) if (nlog_n < sizeof(nlog_buf) - 1) nlog_buf[nlog_n++] = t[i];
}
static void nlog_eol(void) {
    if (nlog_n < sizeof(nlog_buf) - 1) nlog_buf[nlog_n++] = '\n';
    nlog_flush();
}

/* ------------------------------------------------------------------------- *
 * CP15 (system control coprocessor) capture -- the DIRECT proof of the MMU
 * state.  The GME main binary runs PRIVILEGED (SVC) on these bare-metal
 * ARM926 SoCs, so MRC p15 reads are legal and have NO side effects (pure
 * register reads -- no memory access, cannot fault, cannot power the pen off).
 * We ONLY ever MRC (read); never MCR (write) -- nothing about the CPU state is
 * disturbed.  Emitted first thing in the run so even a later crash preserves
 * the answer, to BOTH B:/TTMDUMP.LOG (labelled + decoded) and B:/cpregs.bin
 * (a fixed struct of u32s, documented order below).
 * ------------------------------------------------------------------------- */
#define MRC_P15(crn, op1, crm, op2) __extension__({ unsigned int __v; \
    __asm__ volatile("mrc p15, " #op1 ", %0, " #crn ", " #crm ", " #op2 : "=r"(__v)); __v; })

/* B:/cpregs.bin layout -- 8 little-endian u32s, in THIS order (32 bytes):
 *   [0] magic  = 'C','P','1','5'  (LE 0x35315043) -- file identifier
 *   [1] MIDR   = MRC p15,0,Rd,c0,c0,0   (Main ID: confirm ARM926EJ-S = 0x41069260ish)
 *   [2] SCTLR  = MRC p15,0,Rd,c1,c0,0   (bit0 M=MMU, bit2 C=Dcache, bit12 I=Icache)
 *   [3] TTBR0  = MRC p15,0,Rd,c2,c0,0   (translation table base; &~0x3fff = L1 base)
 *   [4] DACR   = MRC p15,0,Rd,c3,c0,0   (domain access control)
 *   [5] DFSR   = MRC p15,0,Rd,c5,c0,0   (data fault status)
 *   [6] FAR    = MRC p15,0,Rd,c6,c0,0   (fault address)
 *   [7] FCSE   = MRC p15,0,Rd,c13,c0,0  (FCSE PID / context id)
 */
static unsigned int cpregs[8];

static void dump_cp15(void) {
    unsigned int sctlr;
    cpregs[0] = ('C') | ('P' << 8) | ('1' << 16) | ('5' << 24);   /* "CP15" (LE) */
    cpregs[1] = MRC_P15(c0,  0, c0, 0);   /* MIDR  */
    cpregs[2] = sctlr = MRC_P15(c1, 0, c0, 0);   /* SCTLR */
    cpregs[3] = MRC_P15(c2,  0, c0, 0);   /* TTBR0 */
    cpregs[4] = MRC_P15(c3,  0, c0, 0);   /* DACR  */
    cpregs[5] = MRC_P15(c5,  0, c0, 0);   /* DFSR  */
    cpregs[6] = MRC_P15(c6,  0, c0, 0);   /* FAR   */
    cpregs[7] = MRC_P15(c13, 0, c0, 0);   /* FCSE  */

    /* raw struct first (smallest, safest) so the answer is on disk immediately */
    dump(L"B:/cpregs.bin", cpregs, sizeof(cpregs));

    /* human-readable, with the MMU verdict decoded from SCTLR bit0 */
    nlog_s("cp15 MIDR=");  nlog_hex(cpregs[1]); nlog_eol();
    nlog_s("cp15 SCTLR="); nlog_hex(sctlr);
    nlog_s("  MMU=");   nlog_s((sctlr & (1u << 0))  ? "on" : "off");
    nlog_s(" Dcache="); nlog_s((sctlr & (1u << 2))  ? "on" : "off");
    nlog_s(" Icache="); nlog_s((sctlr & (1u << 12)) ? "on" : "off"); nlog_eol();
    nlog_s("cp15 TTBR0="); nlog_hex(cpregs[3]);
    nlog_s(" L1base=");    nlog_hex(cpregs[3] & ~0x3fffu); nlog_eol();
    nlog_s("cp15 DACR=");  nlog_hex(cpregs[4]); nlog_eol();
    nlog_s("cp15 DFSR=");  nlog_hex(cpregs[5]);
    nlog_s(" FAR=");       nlog_hex(cpregs[6]);
    nlog_s(" FCSE=");      nlog_hex(cpregs[7]); nlog_eol();
    nlog_s("==> MMU is ");
    nlog_s((sctlr & (1u << 0)) ? "ON  (0x08004400 IS a live L2 page table)"
                              : "OFF (page-table bytes are inert; flat addressing)");
    nlog_eol();
}

/* ------------------------------------------------------------------------- *
 * Page-table dump + L1->L2 walk.  The real pen's MMU is ON (confirmed: SCTLR
 * bit0=1) with TTBR0=0x08004000, so the L1 table is LIVE and mapped (the MMU is
 * translating through it right now) -- reading it is safe.  We:
 *   (a) dump the full 16KB L1 table (TTBR0 & ~0x3fff .. +0x4000) -> B:/l1pt.bin;
 *   (b) walk all 4096 L1 entries; every COARSE page-table descriptor (low bits
 *       == 0b01) points at a 1KB (256-entry) L2 table at base = entry&0xfffffc00.
 *       Dump each DISTINCT L2 table (deduped) -> B:/l2_XXXXXXXX.bin (hex base),
 *       each GUARDED to a plausible firmware-RAM base first, capped at L2_MAX to
 *       keep the pass short.  Together l1pt.bin + the l2_*.bin give the complete
 *       VA->PA map.
 * This runs EARLY (right after dump_cp15(), before the RAM-region loop / any
 * riskier read) because the page-table contents are now the key deliverable.
 * The L1 read is still guarded to firmware RAM so a wild/zero TTBR0 (e.g. the
 * MMU-off emulator) can never send a 16KB read into an unmapped hole.  Every
 * write is <=16KB (well under the 32KB chunk / 1MB hang limits); the log is
 * flushed before each read so a power-off names the culprit.
 * ------------------------------------------------------------------------- */
#define L2_MAX 64                      /* cap: keep the pass short */
static unsigned int   l2seen[L2_MAX];  /* distinct coarse-PT L2 bases already handled */
static unsigned int   l2cnt;
static unsigned short l2name[20];      /* "B:/l2_" + 8 hex + ".bin" + NUL = 19 */
static void mk_l2name(unsigned int base) {
    static const char hx[] = "0123456789abcdef";
    int i;
    l2name[0]='B'; l2name[1]=':'; l2name[2]='/'; l2name[3]='l'; l2name[4]='2'; l2name[5]='_';
    for (i = 0; i < 8; i++) l2name[6+i] = (unsigned short)hx[(base >> ((7 - i) * 4)) & 0xf];
    l2name[14]='.'; l2name[15]='b'; l2name[16]='i'; l2name[17]='n'; l2name[18]=0;
}
static void dump_page_tables(void) {
    unsigned int ttbr0 = cpregs[3];
    unsigned int l1base = ttbr0 & ~0x3fffu;
    volatile unsigned int *l1p;
    unsigned int i, j;

    if (!(l1base >= 0x08000000u && l1base < 0x08380000u)) {
        nlog_s("pt: L1 SKIP -- TTBR0 base "); nlog_hex(l1base);
        nlog_s(" not in firmware RAM (MMU off?); no page-table dump"); nlog_eol();
        return;
    }

    /* (a) full 16KB L1 table -> B:/l1pt.bin */
    nlog_s("pt: L1 read "); nlog_hex(l1base);
    nlog_s("..");           nlog_hex(l1base + 0x4000u);
    nlog_s(" -> B:/l1pt.bin"); nlog_eol();
    dump(L"B:/l1pt.bin", (void *)l1base, 0x4000);
    nlog_s("pt: L1 done; walking 4096 entries for coarse L2 tables"); nlog_eol();

    /* (b) walk the L1: coarse descriptor (low bits 01) -> L2 base = entry & 0xfffffc00 */
    l1p = (volatile unsigned int *)l1base;
    for (i = 0; i < 4096u; i++) {
        unsigned int e = l1p[i];
        unsigned int base;
        int dup = 0;
        if ((e & 3u) != 1u) continue;              /* only coarse page-table descriptors */
        base = e & 0xfffffc00u;
        for (j = 0; j < l2cnt; j++) if (l2seen[j] == base) { dup = 1; break; }
        if (dup) continue;                         /* dedup: one file per distinct L2 base */
        if (l2cnt >= L2_MAX) {
            nlog_s("pt: L2 cap "); nlog_dec(L2_MAX);
            nlog_s(" reached at L1["); nlog_dec(i); nlog_s("], stopping walk"); nlog_eol();
            break;
        }
        l2seen[l2cnt++] = base;                    /* record (even if skipped) so we don't repeat */
        if (!(base >= 0x08000000u && base < 0x08380000u)) {
            nlog_s("pt: L2 skip base "); nlog_hex(base);
            nlog_s(" (out of RAM range) from L1["); nlog_dec(i); nlog_s("]"); nlog_eol();
            continue;                              /* guard: never read a wild base */
        }
        mk_l2name(base);
        nlog_s("pt: L2 L1["); nlog_dec(i); nlog_s("] base "); nlog_hex(base);
        nlog_s(" -> B:/l2_"); nlog_h8(base); nlog_s(".bin"); nlog_eol();
        dump(l2name, (void *)base, 0x400);         /* 256 entries x 4 = 1KB */
    }
    nlog_s("pt: walk done, "); nlog_dec(l2cnt);
    nlog_s(" distinct coarse L2 base(s) seen"); nlog_eol();
}

/* ------------------------------------------------------------------------- *
 * Progressive low-memory (mask-ROM) probe -- the LAST thing in the pass.
 * Reads increasing ranges [4 .. size) straight from mapped memory into a
 * SEPARATE file per size (B:/mrom_XXXXXXXX.bin, XXXXXXXX = size in hex),
 * smallest-first, each fully opened+written+CLOSED (flushed) before the next
 * larger read.  Address 0 faults on real pens (reset vector) but 4 works, so
 * we start at 4.  If a larger read runs off the mapped ROM the pen powers off
 * -- but every smaller file is already committed, and TTMDUMP.LOG (flushed per
 * line) records the last size that succeeded.  Finer granularity (0x400 steps)
 * than the earlier run, to pin the mapped-ROM boundary and squeeze past it.
 * Largest single write is 0x8000-4 bytes (<= the proven-safe 32KB chunk).
 * ------------------------------------------------------------------------- */
#define LOWMEM_STEP  0x400u
#define LOWMEM_CAP   0x8000u   /* ceiling: keeps each single write <= 32KB */
static unsigned short lowname[21];   /* "B:/mrom_" + 8 hex + ".bin" + NUL = 21 */
static void mk_lowname(unsigned int sz) {
    static const char hx[] = "0123456789abcdef";
    int i;
    /* "B:/mrom_XXXXXXXX.bin" */
    lowname[0]='B'; lowname[1]=':'; lowname[2]='/';
    lowname[3]='m'; lowname[4]='r'; lowname[5]='o'; lowname[6]='m'; lowname[7]='_';
    for (i = 0; i < 8; i++) lowname[8+i] = (unsigned short)hx[(sz >> ((7 - i) * 4)) & 0xf];
    lowname[16]='.'; lowname[17]='b'; lowname[18]='i'; lowname[19]='n'; lowname[20]=0;
}
static void dump_lowmem_progressive(void) {
    unsigned int sz;
    nlog_s("lowmem: probing [4..size) in 0x400 steps up to "); nlog_hex(LOWMEM_CAP);
    nlog_s(" (smallest-first, flush-each; a power-off here loses nothing above)"); nlog_eol();
    for (sz = LOWMEM_STEP; sz <= LOWMEM_CAP; sz += LOWMEM_STEP) {
        mk_lowname(sz);
        /* log the INTENT (and flush) BEFORE the read, so if this size is past
         * the mapped ROM and the pen powers off, the log names the last try. */
        nlog_s("lowmem: try size="); nlog_hex(sz); nlog_eol();
        dump(lowname, (void *)4u, sz - 4u);   /* [4 .. sz): sz-4 bytes from addr 4 */
    }
    nlog_s("lowmem: reached cap "); nlog_hex(LOWMEM_CAP);
    nlog_s(" without power-off (>= that much low memory is mapped)"); nlog_eol();
}

/* NOTE: the earlier READ-ONLY physical NAND boot-block dumper (dump_nand_boot,
 * 2N only) has been REMOVED.  It powered a real pen off mid-read (validated only
 * in the emulator; on real silicon likely a bad-block/ECC or -- now that we know
 * the MMU is ON -- a physical-buffer-mapping fault), and it is not needed for the
 * MMU/page-table goal.  Removing it lets the pass finish cleanly and reach the
 * done cue.  (The mechanism is documented in the firmware-re notes if ever
 * needed again.) */

void main(system_api *apiOrgi) {
    initTT(apiOrgi);

    if (api->fpAkOidPara[First_time_exec] == 0) {
        api->fpAkOidPara[First_time_exec] = 1;
        playSoundNow(MEDIA_START);                   /* start cue */
        nlog_n = 0;
        nlog_s("memimg start"); nlog_eol();

        /* CP15 FIRST: zero-risk register reads that settle "is the MMU on and
         * where is the page table" -- on disk (B:/cpregs.bin + log) before any
         * memory read that could power the pen off. */
        dump_cp15();

        /* PAGE TABLES SECOND: the MMU is ON, so the L1 table at TTBR0 is live +
         * mapped.  Dump it and walk it into its L2 tables NOW -- before the
         * RAM-region loop and before any risky read -- because the page-table
         * CONTENTS (the full VA->PA map) are the key deliverable of this run. */
        dump_page_tables();

        dump(L"B:/mrom_sysapi.bin", apiOrgi, 0x200);
        dump(L"B:/mrom_fwhead.bin", (void *)FWHEAD_BASE, 0x100);

        int i;
        for (i = 0; i < NREG; i++) {
            unsigned int a = regions[i];
            mkname(a);
            dump(nm, (void *)a, 0x8000);          /* 32KB each -- no single large write */
            nlog_s("ram: dumped "); nlog_hex(a); nlog_eol();
        }

        /* CP15, page tables and RAM regions are now on disk + logged.  Mark that
         * phase complete BEFORE the (riskier) low-memory probe, so a power-off
         * there can't cost the rest. */
        log_line(L"B:/TTMDONE.TXT", "memimg done\n", 12);
        nlog_s("ram: complete (B:/TTMDONE.TXT written)"); nlog_eol();

        /* LAST: progressive mask-ROM probe -- if it powers the pen off, every
         * file above (CP15, page tables, sysapi/fwhead, RAM regions) is already
         * committed. */
        dump_lowmem_progressive();

        done = 1;
    }

    if (done && api->is_audio_playing() == 0) {
        playSoundNow(MEDIA_DONE);                    /* done cue (repeats until power-off) */
    }
}
