#!/usr/bin/env python3
"""make_gme.py -- build a complete tiptoi .gme from a C main binary + media files.

The common "C project" case: your compiled main binary (one per pen) runs on product load and
plays your bundled media through the firmware. NO scripts, NO games -- just binary + media.

Fully self-contained -- derived from the firmware we reverse-engineered; NO tt-homebrew, no
build.js/gmelib/node, and NO reference .gme needed:

  * Header validated region is SYNTHESISED from constants the firmware's mount check accepts:
    magic (0x08 == 0x238b); the CHOMPTECH format string as the length-prefixed comment at 0x20;
    an empty language field at 0x59 (gme_check_language@0x0802ae74 accepts empty -> defaults to
    GERMAN); XOR key at 0x1C (see below).
  * product id  -> header[0x14]  (must equal the OID the pen looks for; --product-id, default 42).
  * media file table -> header[0x04]: N pairs of (u32 file-offset, u32 length). Media index i is the
    i-th pair. Content is XOR-obfuscated with the pass-through rule (key = header[0x1C]); the firmware
    decrypts it on read. Your binary plays media #i with:
        play_sound(*p_filehandle_current_gme, offset_i, length_i)   (system_api +0x2c / +0x38|+0x4c)
  * embedded main binary table(s) -> header 0xA0 (ZC3201) / 0xA8 (2N) / 0xC8 (3L), via inject_gme.
  * trailing additive checksum.

tttool compatibility: tttool's parser walks EVERY segment, and it treats a header offset of 0 as
"seek to offset 0 and parse the file start" (not "absent") for the segments it reads via `indirection`
-- Scripts@0x00, Media@0x04, Additional-script@0x0C, Games@0x10, Initial-registers@0x18,
Welcome-playlists@0x71. So those all point at real, VALID-BUT-EMPTY structures here (a shared zero
word: u16/u32 count 0). Segments read via `maybeIndirection` (0x60, 0x94, binaries) DO treat 0 as
absent, so those stay 0.

Media index names: --media-header emits a C header mapping each media file's basename (sans
extension) to its index (MEDIA_START/MEDIA_DONE/...). One ordered --media list drives both the media
table and the header, so names and indices can't drift.

XOR pass-through rule (matches the firmware media decrypt): a media byte n is left unchanged if
n in {0x00, 0xFF, key, key^0xFF}, else n ^= key.  The transform is its own inverse.
"""
import argparse, os, re, struct
import inject_gme

MAGIC_08   = 0x0000238B
HDR        = 0x100
XOR_KEY    = 0x39                                                   # header[0x1C] "raw" xor (tttool knownRawXOR)
MEDIA_XOR  = 0xAD                                                   # the key the FIRMWARE actually applies to media
                                                                    # (tttool knownXOR for rawXor 0x39). Header stores the
                                                                    # raw 0x39; media must be encrypted with 0xAD or it
                                                                    # decrypts to garbage -> medialib_open fails -> silence.
COMMENT    = b"CHOMPTECH DATA FORMAT CopyRight 2009 Ver2.4.0316"    # 48 bytes; tttool reads it as the comment
DATE       = b"20111024"                                            # 8-byte build date (arbitrary but valid)


def xor_passthrough(data: bytes, key: int) -> bytes:
    keep = {0x00, 0xFF, key, key ^ 0xFF}
    return bytes(n if n in keep else n ^ key for n in data)


def synth_header() -> bytearray:
    """Build the firmware-validated header region (0x00..0x60) from constants -- no --ref needed."""
    h = bytearray(HDR)
    struct.pack_into("<I", h, 0x08, MAGIC_08)      # magic, required by gme_mount_check_product
    h[0x1C] = XOR_KEY                              # media obfuscation key
    h[0x20] = len(COMMENT)                         # tttool comment length (0x30)
    h[0x21:0x21 + len(COMMENT)] = COMMENT
    o = 0x21 + len(COMMENT)                        # = 0x51
    h[o:o + len(DATE)] = DATE                      # 8-byte date at 0x51..0x59
    # 0x59.. language: left zero -> gme_check_language accepts (defaults to GERMAN)
    return h


def media_idents(media_paths):
    """Stable C identifier per media file: MEDIA_<BASENAME-sans-ext, uppercased, non-alnum->_>, deduped."""
    used, idents = {}, []
    for p in media_paths:
        base = os.path.splitext(os.path.basename(p))[0]
        ident = "MEDIA_" + re.sub(r"[^0-9A-Za-z]", "_", base).upper()
        if len(ident) > 6 and ident[6].isdigit():
            ident = "MEDIA__" + ident[6:]
        if ident in used:
            used[ident] += 1
            ident = "%s_%d" % (ident, used[ident])
        else:
            used[ident] = 0
        idents.append(ident)
    return idents


def media_header_text(media_paths):
    idents = media_idents(media_paths)
    w = max([len(x) for x in idents] + [len("MEDIA_COUNT")])
    lines = ["/* generated by make_gme.py -- do not edit */", "#ifndef GME_MEDIA_H", "#define GME_MEDIA_H", ""]
    for i, ident in enumerate(idents):
        lines.append("#define %-*s %d" % (w, ident, i))
    lines.append("#define %-*s %d" % (w, "MEDIA_COUNT", len(media_paths)))
    lines += ["", "#endif", ""]
    return "\n".join(lines)


def build(product_id, media_paths, injections):
    body = synth_header()
    xor_key = body[0x1C]

    def put(off, val):
        struct.pack_into("<I", body, off, val)

    # A single 4-byte zero word that every MANDATORY-but-empty `indirection` segment points at:
    # Additional-script (u16 count), Games (u32 count), Initial-registers (u16 count), Welcome
    # playlistlist (u16 count) all read 0 = empty here. tttool follows a 0 *offset* into the file
    # start (parsing garbage), so these must point at a real zero word -- not be 0.
    empty_off = len(body); body += struct.pack("<I", 0)

    # script table (header[0x00]): getScripts reads last_oid, 0, first_oid, 0, then per-OID pointer.
    # One OID = the product id, with a null (0xFFFFFFFF -> maybeIndirection = absent) script line.
    while len(body) % 4: body += b"\x00"
    script_off = len(body)
    oid = product_id & 0xFFFF
    body += struct.pack("<HHHHI", oid, 0, oid, 0, 0xFFFFFFFF)

    # media file table (header[0x04]): N (offset,length) pairs, then the XOR'd content.
    while len(body) % 4: body += b"\x00"
    media_tbl_off = len(body)
    body += b"\x00" * (len(media_paths) * 8)
    entries = []
    for path in media_paths:
        raw = open(path, "rb").read()
        while len(body) % 4: body += b"\x00"
        off = len(body)
        body += xor_passthrough(raw, MEDIA_XOR)
        entries.append((off, len(raw)))
    for i, (off, ln) in enumerate(entries):
        struct.pack_into("<II", body, media_tbl_off + i * 8, off, ln)

    put(0x00, script_off)                                    # Scripts        (indirection, mandatory)
    put(0x04, media_tbl_off if media_paths else empty_off)   # Media          (indirection, mandatory)
    put(0x08, MAGIC_08)
    put(0x0C, empty_off)                                     # Additional-script (indirection) -> count 0
    put(0x10, empty_off)                                     # Games             (indirection) -> count 0
    put(0x14, product_id)
    put(0x18, empty_off)                                     # Initial-registers (indirection) -> count 0
    put(0x60, 0)                                             # additional media  (maybeIndirection: 0 = absent)
    put(0x71, empty_off)                                     # Welcome playlists (indirection) -> count 0
    put(0x94, 0)                                             # special-OID list  (maybeIndirection: 0 = absent)
    body[0xA4] = 1                                           # "header contains offsets" flag

    body += struct.pack("<I", 0)                             # checksum slot for inject's [:-4]
    return inject_gme.inject(bytes(body), injections)


def media_entries(gme: bytes):
    """Read the (offset,length) media table as the firmware would: pairs until the first content byte."""
    tbl = struct.unpack_from("<I", gme, 0x04)[0]
    if tbl == 0:
        return []
    out, o, first = [], tbl, None
    while first is None or o < first:
        off, ln = struct.unpack_from("<II", gme, o)
        if off == 0:
            break
        out.append((off, ln))
        first = off if first is None else min(first, off)
        o += 8
    return out


def main():
    ap = argparse.ArgumentParser(description="Build a C-binary + media .gme (self-contained, no other GME features).")
    ap.add_argument("-o", "--out", required=True)
    ap.add_argument("--product-id", type=lambda s: int(s, 0), default=42,
                    help="product id / power-on OID (header 0x14); default 42 (the 'taschenrechner' printout)")
    ap.add_argument("-b", "--bin", action="append", default=[], metavar="PEN=FILE",
                    help="main binary per pen (2N=..., ZC3201=..., 3L=...); repeatable")
    ap.add_argument("-m", "--media", action="append", default=[], metavar="FILE",
                    help="media file (OggS or RIFF/WAV); order = media index 0,1,2,...; repeatable")
    ap.add_argument("--media-header", metavar="FILE", help="emit a C header of MEDIA_<name>->index #defines")
    ap.add_argument("-n", "--name", default="main", help="8-char binary entry name")
    ap.add_argument("--verify", action="store_true")
    a = ap.parse_args()

    injections = []
    for spec in a.bin:
        pen, path = spec.split("=", 1)
        injections.append((pen, open(path, "rb").read(), a.name))
    if not injections:
        ap.error("give at least one --bin PEN=FILE")

    if a.media_header:
        open(a.media_header, "w").write(media_header_text(a.media))
        print("wrote %s: %s" % (a.media_header, ", ".join("%s=%d" % (n, i) for i, n in enumerate(media_idents(a.media)))))

    out = build(a.product_id, a.media, injections)
    open(a.out, "wb").write(out)
    print("wrote %s (%d bytes)  product_id=%d  media=%d  bins=%d  (header synthesised)"
          % (a.out, len(out), a.product_id, len(a.media), len(injections)))
    for i, (off, ln) in enumerate(media_entries(out)):
        print("  media[%d] @0x%x len=%d" % (i, off, ln))

    if a.verify:
        ok = True
        for pen, binary, _ in injections:
            r = inject_gme.extract(out, pen)
            same = r is not None and r[2] == binary
            ok &= same
            print("  VERIFY bin %-8s: %s" % (pen, "loader extracts identical binary" if same else "FAIL"))
        for i, (path, (off, ln)) in enumerate(zip(a.media, media_entries(out))):
            dec = xor_passthrough(out[off:off + ln], MEDIA_XOR)
            same = dec == open(path, "rb").read()
            ok &= same
            print("  VERIFY media[%d] %-16s: %s" % (i, os.path.basename(path),
                  "round-trips (decrypt == source)" if same else "FAIL"))
        raise SystemExit(0 if ok else 1)


if __name__ == "__main__":
    main()
